# Naive Bayes

## Estudo 01 - Classificação de Risco de Crédito

### Objetivo

Este projeto foi desenvolvido com o objetivo de compreender os fundamentos da classificação supervisionada utilizando o algoritmo Naive Bayes.

Durante o estudo, pude aplicar o algoritmo em um problema de risco de crédito, realizando previsões com base nas características dos clientes presentes na base de dados.

Mais do que obter uma previsão, o foco deste projeto foi entender como resolver um problema simples de aprovação de crédito
usando um fluxo básico de Machine Learning.

**Base de Risco Credito**

##### Importação das Blibliotecas

In [2]:
import pandas as pd

from sklearn.preprocessing import LabelEncoder

import pickle

In [12]:
#Leitura da Base
base_risco_credito = pd.read_csv(r'content\risco_credito\risco_credito.csv')
base_risco_credito.head()

       historia divida garantias     renda     risco
0          ruim   alta   nenhuma      0_15      alto
1  desconhecida   alta   nenhuma     15_35      alto
2  desconhecida  baixa   nenhuma     15_35  moderado
3  desconhecida  baixa   nenhuma  acima_35      alto
4  desconhecida  baixa   nenhuma  acima_35     baixo

In [13]:
# Criando variaveis preditoras e previsoras
X_risco_credito = base_risco_credito.iloc[:,0:4]
Y_risco_credito = base_risco_credito.iloc[:,4]

In [14]:
#Features
X_risco_credito.head()

       historia divida garantias     renda
0          ruim   alta   nenhuma      0_15
1  desconhecida   alta   nenhuma     15_35
2  desconhecida  baixa   nenhuma     15_35
3  desconhecida  baixa   nenhuma  acima_35
4  desconhecida  baixa   nenhuma  acima_35

In [15]:
#Variavel Resposta
Y_risco_credito.head()

0        alto
1        alto
2    moderado
3        alto
4       baixo
Name: risco, dtype: str

In [16]:
# Importar o módulo da biblioteca LabelEncoder


# Salvar os objetos LabelEncoder de cada coluna
encoders = {}

# Salvar os mapeamentos categoria -> número
mapeamentos = {}

# Loop para percorrer todas as features e transformar seus domínios em labels numéricos
for coluna in X_risco_credito.columns:

    # Instancia um LabelEncoder para a coluna atual
    encoder = LabelEncoder()

    # Aprende as categorias da coluna e realiza a transformação para números
    X_risco_credito[coluna] = encoder.fit_transform(
        X_risco_credito[coluna]
    )

    # Salva o encoder para reutilização futura
    encoders[coluna] = encoder

    # Cria um dicionário para documentar o mapeamento realizado
    mapeamentos[coluna] = {}

    # Percorre as categorias aprendidas e registra o número atribuído a cada uma
    for indice, valor in enumerate(encoder.classes_):
        mapeamentos[coluna][valor] = indice

# Exibe todos os mapeamentos realizados
print(mapeamentos)

{'historia': {'boa': 0, 'desconhecida': 1, 'ruim': 2}, 'divida': {'alta': 0, 'baixa': 1}, 'garantias': {'adequada': 0, 'nenhuma': 1}, 'renda': {'0_15': 0, '15_35': 1, 'acima_35': 2}}

In [20]:
# Salva os dados pré-processados (X e Y) em um arquivo .pkl
# para reutilização futura sem precisar executar novamente
# toda a etapa de tratamento e codificação dos dados.

with open(r'content\risco_credito\risco_credito.pkl', 'wb') as f:
    pickle.dump([X_risco_credito, Y_risco_credito], f)

**Naive Bayes**

In [21]:
from sklearn.naive_bayes import GaussianNB

In [22]:
naive_risco_credito = GaussianNB()
naive_risco_credito.fit(X_risco_credito,Y_risco_credito)

GaussianNB()

In [23]:
print(mapeamentos)

{'historia': {'boa': 0, 'desconhecida': 1, 'ruim': 2}, 'divida': {'alta': 0, 'baixa': 1}, 'garantias': {'adequada': 0, 'nenhuma': 1}, 'renda': {'0_15': 0, '15_35': 1, 'acima_35': 2}}

In [26]:
# história de crédito
# boa = 0
# desconhecida = 1
# ruim = 2

# dívida
# alta = 0
# baixa = 1

# garantias
# adequada = 0
# nenhuma = 1

# renda
# 0_15 = 0
# 15_35 = 1
# acima_35 = 2

previsao = naive_risco_credito.predict([
    
    # Cliente 1
    # História: boa
    # Dívida: baixa
    # Garantias: adequada
    # Renda: acima_35
    [0, 1, 0, 2],

    # Cliente 2
    # História: ruim
    # Dívida: alta
    # Garantias: nenhuma
    # Renda: 0_15
    [2, 0, 1, 0],

    # Cliente 3
    # História: desconhecida
    # Dívida: baixa
    # Garantias: nenhuma
    # Renda: 15_35
    [1, 1, 1, 1],

    # Cliente 4
    # História: boa
    # Dívida: alta
    # Garantias: adequada
    # Renda: 15_35
    [0, 0, 0, 1],

    # Cliente 5
    # História: ruim
    # Dívida: baixa
    # Garantias: adequada
    # Renda: acima_35
    [2, 1, 0, 2]
])

print(previsao)

['baixo' 'alto' 'alto' 'moderado' 'baixo']

C:\Users\lucas\AppData\Local\Programs\Python\Python313\Lib\site-packages\sklearn\utils\validation.py:2827: UserWarning: X does not have valid feature names, but GaussianNB was fitted with feature names
  warnings.warn(

In [27]:
previsao

array(['baixo', 'alto', 'alto', 'moderado', 'baixo'], dtype='<U8')

In [31]:
# classes_
# Mostra quais são as classes que o modelo aprendeu.
# No problema de risco de crédito geralmente:
# alto = risco alto
# moderado = risco moderado
# baixo = risco baixo
#
# Exemplo:
# ['alto' 'baixo']
print(naive_risco_credito.classes_)

['alto' 'baixo' 'moderado']

In [33]:
# class_count_
# Quantidade de registros de cada classe utilizados no treinamento.
#
# Exemplo:
# [7. 7.]
#
# Significa que:
# 7 exemplos pertencem à primeira classe
# 7 exemplos pertencem à segunda classe
print(naive_risco_credito.class_count_)

[6. 5. 3.]

In [34]:
# class_prior_
# Probabilidade inicial (a priori) de cada classe.
#
# É calculada antes de analisar as características
# do cliente (história, dívida, garantias e renda).
#
# Exemplo:
# [0.5 0.5]
#
# Significa:
# 50% dos registros são da primeira classe
# 50% dos registros são da segunda classe
print(naive_risco_credito.class_prior_)

[0.42857143 0.35714286 0.21428571]

## Estudo 02 - Classificação de Risco de Crédito